import { createTheme, MantineTheme } from '@mantine/core';

export const theme = createTheme({
  colors: {
    primary: [
      '#FFECEE',
      '#FFD8DB',
      '#FFBDC1',
      '#FF9EA3',
      '#FF7C83',
      '#FF5A5F',
      '#CC484C',
      '#993639',
      '#662426',
      '#331213',
    ],
    secondary: [
      '#E6F9F7',
      '#CCF2EF',
      '#99E5DF',
      '#66D9CF',
      '#33CCBF',
      '#00A699',
      '#00857A',
      '#00645C',
      '#00423D',
      '#00211F',
    ],
    accent: [
      '#FFEEEC',
      '#FFDCD8',
      '#FFB9B0',
      '#FF9689',
      '#FF7D61',
      '#FC642D',
      '#CA5024',
      '#973C1B',
      '#652813',
      '#32140A',
    ],
    success: [
      '#E6F9F4',
      '#CCF2E9',
      '#99E5D2',
      '#66D9BC',
      '#33CCA6',
      '#00B797',
      '#009279',
      '#006E5B',
      '#00493C',
      '#00251E',
    ],
    warning: [
      '#FFF9E6',
      '#FFF3CC',
      '#FFE699',
      '#FFDA66',
      '#FFCE33',
      '#FFBD00',
      '#CC9700',
      '#997100',
      '#664B00',
      '#332600',
    ],
    error: [
      '#FFECEF',
      '#FFD8DE',
      '#FFB0BD',
      '#FF899D',
      '#FF617C',
      '#FF385C',
      '#CC2D49',
      '#992137',
      '#661624',
      '#330B12',
    ],
    neutral: [
      '#FFFFFF',
      '#F7F7F7',
      '#E5E5E5',
      '#CCCCCC',
      '#999999',
      '#666666',
      '#333333',
      '#222222',
      '#111111',
      '#000000',
    ],
    action: [
      '#F7FFDC',
      '#EEFFB8',
      '#D8FF80',
      '#C3FF33',
      '#B3FF00',
      '#8EC600',
      '#689400',
      '#547300',
      '#273500',
      '#131A00',
    ],
  },
  primaryColor: 'primary',
  fontFamily: 'Inter, Roboto, sans-serif',
  headings: {
    fontFamily: 'Inter, Roboto, sans-serif',
    sizes: {
      h1: { fontSize: '2rem', lineHeight: '1.3', fontWeight: '700' },
      h2: { fontSize: '1.75rem', lineHeight: '1.35', fontWeight: '700' },
      h3: { fontSize: '1.5rem', lineHeight: '1.4', fontWeight: '600' },
      h4: { fontSize: '1.25rem', lineHeight: '1.4', fontWeight: '600' },
      h5: { fontSize: '1.125rem', lineHeight: '1.45', fontWeight: '600' },
      h6: { fontSize: '1rem', lineHeight: '1.5', fontWeight: '600' },
    },
  },
  spacing: {
    xs: '0.25rem',
    sm: '0.5rem',
    md: '1rem',
    lg: '1.5rem',
    xl: '2rem',
  },
  fontSizes: {
    xs: '0.75rem',
    sm: '0.875rem',
    md: '1rem',
    lg: '1.125rem',
    xl: '1.25rem',
  },
  radius: {
    xs: '0.125rem',
    sm: '0.25rem',
    md: '0.5rem',
    lg: '1rem',
    xl: '1.5rem',
  },
  shadows: {
    xs: '0 1px 2px rgba(0, 0, 0, 0.05)',
    sm: '0 1px 3px rgba(0, 0, 0, 0.1), 0 1px 2px rgba(0, 0, 0, 0.06)',
    md: '0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06)',
    lg: '0 10px 15px -3px rgba(0, 0, 0, 0.1), 0 4px 6px -2px rgba(0, 0, 0, 0.05)',
    xl: '0 20px 25px -5px rgba(0, 0, 0, 0.1), 0 10px 10px -5px rgba(0, 0, 0, 0.04)',
  },
  components: {
    Button: {
      styles: (theme: MantineTheme) => ({
        root: {
          '&[dataVariant="primary"]': {
            backgroundColor: theme.colors.primary[5],
            color: theme.colors.neutral[0],
            fontWeight: 600,
            '&:hover': {
              backgroundColor: theme.colors.primary[6],
            },
          },
          '&[dataVariant="secondary"]': {
            backgroundColor: theme.colors.secondary[5],
            color: theme.colors.neutral[0],
            fontWeight: 600,
            '&:hover': {
              backgroundColor: theme.colors.secondary[6],
            },
          },
          '&[dataVariant="outline"]': {
            borderColor: theme.colors.primary[5],
            color: theme.colors.primary[5],
            fontWeight: 600,
            '&:hover': {
              backgroundColor: theme.colors.primary[0],
            },
          },
          '&[dataVariant="ghost"]': {
            color: theme.colors.primary[5],
            fontWeight: 600,
            '&:hover': {
              backgroundColor: theme.colors.primary[0],
            },
          },
          '&[dataVariant="action"]': {
            backgroundColor: theme.colors.action?.[4] || '#B3FF00',
            color: theme.colors.neutral[9],
            fontWeight: 600,
            '&:hover': {
              backgroundColor: theme.colors.action?.[5] || '#8EC600',
            },
          },
        },
      }),
    },
    Card: {
      styles: (theme: MantineTheme) => ({
        root: {
          '&[dataVariant="filled"]': {
            backgroundColor: theme.colors.neutral[1],
          },
          '&[dataVariant="outline"]': {
            borderColor: theme.colors.neutral[2],
          },
          '&[dataVariant="elevated"]': {
            boxShadow: theme.shadows.sm,
          },
        },
      }),
    },
    Text: {
      styles: (theme: MantineTheme) => ({
        root: {
          '&[dataVariant="heading"]': {
            fontWeight: 700,
            color: theme.colors.neutral[9],
          },
          '&[dataVariant="body"]': {
            fontSize: theme.fontSizes.md,
            color: theme.colors.neutral[7],
          },
          '&[dataVariant="caption"]': {
            fontSize: theme.fontSizes.xs,
            color: theme.colors.neutral[5],
          },
          '&[dataVariant="highlight"]': {
            color: theme.colors.primary[5],
            fontWeight: 500,
          },
          '&[dataVariant="quantity"]': {
            fontFamily: 'Inter, sans-serif',
            fontWeight: 600,
            fontSize: '14px',
            lineHeight: '18px',
            minWidth: '20px',
            textAlign: 'center',
            color: theme.colors.neutral[9],
          },
          '&[dataProductName]': {
            fontFamily: 'Inter, sans-serif',
            fontSize: '12px',
            lineHeight: '18px',
            fontWeight: 400,
            color: '#667085',
            marginBottom: '0px',
            whiteSpace: 'nowrap',
            overflow: 'hidden',
            textOverflow: 'ellipsis',
            letterSpacing: '0%',
            textAlign: 'center',
          },
          '&[dataOriginalPrice]': {
            fontFamily: 'Inter, sans-serif',
            fontSize: '10px',
            lineHeight: '18px',
            fontWeight: 500,
            textAlign: 'center',
            textDecoration: 'line-through',
            color: '#667085',
            marginBottom: '2px',
            zIndex: 15,
          },
          '&[dataPrice]': {
            fontFamily: 'Inter, sans-serif',
            fontWeight: 600,
            fontSize: '12px',
            lineHeight: '18px',
            textAlign: 'center',
            color: '#101828',
            zIndex: 15,
          },
        },
      }),
    },
    Container: {
      defaultProps: {
        px: 'md',
      },
    },
  },
});
